### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by doogalbear** [push-things/dj-diabetes#9]
I'm looking for something similar to this setup. I was wanting to know, 
1. Are you you still developing this software? 
2. Is this just for Diabetics? (my wife has stage 4 cancer and I'm looking for something to help keep track of vitals and such like this software) 
3. Do you have a demo setup somewhere, I would like to see it in action. 
4. If you aren't developing this, do you know of a system similar that is self host-able I can get?

TIA, 
Douglas

**Comment by foxmask** [comment]
Hi,
As I am not diabetic myself, I just make update of the framework to make this project up-to-date.
At the beginning I made this project for a friend, but since I published it, I have no more news.
So I dont know what to do to improve the project for diabetics 
It looks like, with others comments you could read in others issues, that the project will be fine, if it could use the data from the injector, but those thing are closed source.
I dont have any live demo available

About your wife, i'm very very sorry for her cancer 😶
I dont know any project that deal with this

But if you want, I can make another project for you, I 'll just need to have a lot of details about the metrics you need, the exam you want to track and so on.
If you are interesting I'll drop you my email to directly exchange on that topic?
Regards

**Comment by foxmask** [comment]
On Reddit you can find self hosted project and may be also on hackernews

**Comment by foxmask** [comment]
you can have a look at ths at least https://camo.githubusercontent.com/b2c11eb497df33822d45e263cc845029550dfdd7/687474703a2f2f666f786d61736b2e747269676765722d68617070792e65752f7374617469632f323031342f30362f676c75636f73655f6d616e616765722d31303234783737312e706e67

**Comment by doogalbear** [comment]
Thank you for your offer. I'm interested. A few things before starting. 

1. I like the layout of your [example site](https://camo.githubusercontent.com/b2c11eb497df33822d45e263cc845029550dfdd7/687474703a2f2f666f786d61736b2e747269676765722d68617070792e65752f7374617469632f323031342f30362f676c75636f73655f6d616e616765722d31303234783737312e706e67) you sent. It shows most of what I would want. I do need more and I can provide what I would like it to show. Especially the chart. I could a few of those. Haven't seen charts on any programs so far. 
2. $$ I'm not rich and usually go for open source when possible. Cancer is costly enough. :(
3. This has to be user friendly for the elderly (mother-in-law) to understand. 
4. shareable through Android app preferably. Easy for others to access than website and sync(notifications of updates)
5. SelfHost on RPI3

I did go to college for programming about 20 years ago, and before my wife got sick with cancer, I had created a few little apps for us to keep track of medications for our doctor. After getting sick, I created another that kept track of blood work with chart to show how she was doing while in treatment. Sadly, I can't find this one at the moment and I don't have time or patience to do programming anymore. I spend most of my time taking care of my wife and typing up daily logs (using markdown) to keep track of her progress for us, family, and Hospice nurses. Besides, I forgot most of what I have learned anyway. Especially, arrays. They were always the hardest to get for me. 

The programs I currently use:
**Android**
+ [tagspaces](https://play.google.com/store/apps/details?id=org.tagspaces.androidle)
+ [notes](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes)
+ [Opentasks](https://play.google.com/store/apps/details?id=org.dmfs.tasks)
+ [Nextcloud](https://play.google.com/store/apps/details?id=com.nextcloud.client)
+ [Wordpress](https://play.google.com/store/apps/details?id=org.wordpress.android)
+ [Grok Notes](https://play.google.com/store/apps/details?id=com.grok.notes)

**Linux**
+ [Qownnotes](http://www.qownnotes.org/)
+ Nextcloud sync

**Chromebook**
+ various markdown editors - can't remember names at moment

Need something I can share with family members to keep them better updated without me having to repeat myself. An app that would autosync would be awesome. [MyOwnNotes](https://play.google.com/store/apps/details?id=org.aykit.MyOwnNotes) for android does this I think. There version requires owncloud app and not nextcloud, so can't use. :( 
***A Kanban type program that autoupdated would be nice.*** 
Anyway, if you are still up to the task, let me know.

Douglas

**Comment by foxmask** [comment]
Hi,
So, first of all, I've no knowledge in programming on Android   
I know a kanban project like, named taiga.
And fortunately, with another project I've written, I'm able to create cards in taiga
So I'll be able to automatically create card from "new project health somthing" to https://taiga.io/

For a user interface, I could start by simple forms to fill and clean data to display to avoid to loose the user.

You spoke about money, but that does not come to my mind. I build free and open source app since '98, for sharing, helping, exchanging , not earning money.

If thoses details are enough for you, let le know.

**Comment by foxmask** [comment]
To be reopened in case news info could be provided
